idf_component_register(
    SRCS
        "rom_loader.c"
        "game_runtime.c"
        "gb_emu.c"
        "gb_audio.c"
        "minigb_apu.c"
        "game_2048.c"
        "mpu6050.c"
    INCLUDE_DIRS
        "."
        "../user"
    REQUIRES
        lvgl
        esp_partition
        driver
        esp_timer
        fatfs
        sdmmc
)
